### PR TITLE
Fix #805 don't `blur()` the trigger after a clipboard action

### LINKED ISSUE #805: Trigger loses focus after copy event
## 🐛 Bug Report

Setting keyboard focus on one of the "Copy" buttons and activating it, focus is then lost/reset to the start of the page. While browsers try to error-correct for this (meaning that a subsequent Tab moves to the next focusable element), the issue becomes evident when using AT (e.g. Chrome/JAWS, activate the button, then use reading keys to carry on reading...focus was moved back right to the start of the page).

Note that this current behaviour is a regression from what was fixed originally in https://github.com/zenorocha/clipboard.js/pull/419

This is a repost of https://github.com/zenorocha/clipboard.js/issues/695 which was closed without reason.

### Have you read the [Contributing Guidelines on issues](https://github.com/zenorocha/clipboard.js/blob/master/contributing.md)?

Yes

### Expected Behaviour

Ideally, focus should remain on the "Copy" button, but I'm assuming this was not done in order to "clear" the visual style of the button. Perhaps this needs to dynamically set a class immediately after a copy operation was carried out, which suppresses/changes the styling (maybe suppressing the tooltip, OR adding some indicator like a tick that shows it was indeed copied), and clearing that class again as soon as the button loses focus.

### Actual Behaviour

Focus is lost/reset after the "Copy" button is activated. While browsers do try to error-correct for when focus is lost, this error correction doesn't work in some situations - such as when JAWS screen reader is running. For this reason, focus should never simply be cleared/`blur()`red, but handled explicitly.

See this video, using Chrome and JAWS screen reader: `Tab` to the button - note that `document.activeElement` (as seen in the developer tools console) is now the button. Activate the button with `Enter`. `document.activeElement` is `body`, and because focus is lost/reset, JAWS goes right back to the start of the document. Using cursor keys (used by JAWS to proceed reading), you see that JAWS starts reading again right from the very start of the page.

https://user-images.githubusercontent.com/895831/163347810-0da9b0c4-652a-43f6-ab51-d62a57c85120.mp4

### To Reproduce

1. Set keyboard focus to a "Copy" button (`Tab` to it). `document.activeElement` is the button
2. Activate the button (`Enter`)
3. Note that the `document.activeElement` is now the `body`

### Browsers Affected

All

### Operational System

All

### PR DESCRIPTION
**Pull request by patrickhlauke**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

This PR reintroduces the behavior that used to be in clipboard.js following https://github.com/zenorocha/clipboard.js/pull/419 but that has since been reverted for some reason. As such, after a clipboard action, focus will remain/be on the trigger element, rather than the body. If applications rely on the focus to be gone/removed from the trigger button, they'll need to adapt to this.

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] New/updated tests are included

I didn't target v2.x branch because it looks wildly out of date.

**Other information:**

I'm not too hot on writing tests, so rather than just removing the check to see if focus is now on the body, it should probably explicitly check that focus remained on the trigger. However, not quite sure how to do that - my knowledge of test harnesses etc is pretty basic.

Closes #805

### CODE REVIEW

File: test/clipboard.js [hunk 1]
```diff
@@ -180,7 +180,6 @@ describe('Clipboard', () => {
 
         e.clearSelection();
 
-        assert.equal(selectedElem, document.body);
```
Comment (obetomuniz) [inline test/clipboard.js:183]: Hey, could update this test to ensure that current `document.activeElement` is the trigger? You can use something using the following approach:

```javascript
    it('should clear text selection', (done) => {
      let clipboard = new Clipboard('.btn');

      clipboard.on('success', (e) => {
        let selectedText = window.getSelection().toString();

        e.clearSelection();

        let selectedElem = document.activeElement;

        assert.equal(selectedElem, e.trigger);
        assert.equal(selectedText, '');

        done();
      });

      clipboard.onClick(global.event);
    });
```

As you can see, it moves `e.clearSelection();` a few lines up to run it as soon as the library is called and replace `assert.equal(selectedElem, document.body);` that you removed for `assert.equal(selectedElem, e.trigger);`, which makes possible ensure that the current element focused is the element that calls the library.

**Review by obetomuniz — CHANGES_REQUESTED** [review]
Looks great to me. I just left feedback to consider before merging related to the test related to the PR. Thanks a lot for the PR.

File: test/clipboard.js (hunk 1 above)
Comment (patrickhlauke) [reply test/clipboard.js:183]: Wonderful, thank you. I took your proposed test (but tweaked the `it('....')` statement slightly.

**Comment by patrickhlauke** [comment]
wonderful! thank you.

**Review by helderburato — APPROVED** [review]
Great job! Thanks for the contribution.
